#import "../../../../assets/exam_template.typ": *

#show: doc => exam(
  [Discrete Mathematics],
  [Bachelor in Artificial Intelligence],
  datetime(year: 2026, month: 5, day: 21),
  is_final: true,
  checksum: false,
  doc,
)

=

+
  / Counting: From a set of $k+1$ vertices, to form a complete graph, we must form all possibles edges, which are all the possible pairs of distinct vertices.
    The edges are thus all the possible 2-subsets we can form from the set of $k+1$ vertices, so it's an "$k+1$ choose $2$" combination.
    So the number of edges of $G_(k+1)$ is
    $
      abs(E) = binom(k+1, 2) = (k+1)! / (2! (k-1)!) = (k (k+1)) / 2
    $

  / Graph theory: According to the handshaking theorem:
    $
      sum_(v in V) k(v) = 2 abs(E) <=> abs(V) k = 2 abs(E) <=> abs(E) = (k (k+1)) / 2
    $

+
  - Base step: from (a), $abs(E_(k+1)) = binom(k+1, 2) = (k (k+1) ) / 2 = (k (k+1)) / 2 + k dot (k + 1 - k - 1)$. So the result holds for $n=k+1$.
  - Induction step: let's assume the equality holds for a given $n >= k+1$.
    To form $G_(n+1)$, we add $k$ edges, so
    $
      abs(E_(n+1)) = abs(E_(n)) + k =(k (k+1)) / 2 + k dot (n-k-1) + k = (k (k+1)) / 2 + k dot ((n+1)-k-1).
    $
    The equality thus holds for $n+1$ too.
  By induction, it holds for all $n >= k+1$.

+ It is regular for $n=k+1$, since it is complete.
  Then, since the sequence is generated by adding vertices and edges, starting from the $(k+1)$-complete graph, in any $G_n$, all vertices have at least degree $k$. Also, starting from $G_(k+2)$, at least $k$ vertices have degree $k+1$. So every $G_n$ generated after that contains a single vertex of degree $k$, and at least $k$ other vertices with a higher degree. This graph thus cannot be regular.




=

+ The output graph is initialized with a single vertex and no edge. Then, for a total of $abs(V) - 1$ times, we add exactly one vertex and one edge to this graph. In the end, it thus has $abs(V)$ vertices, and $abs(V) - 1$ edges. It is also connected, as every edge is formed by connecting an existing vertex to a new one, which is one of its predecessors in $G$. This output is therefore a spanning tree of $G$.

+ This is like Dijkstra, but stopping when all vertices have been found, and writing the output as a tree.
  The output, with weights included, is

  #figure(
    raw-render(
      ```dot
      graph {
        layout=neato
        start=3
        node[shape=circle margin=0 fontsize=20];
        edge [fontsize=20];
        1 -- 2 [label="3"];
        1 -- 3 [label="2"];
        2 -- 5 [label="1"];
        2 -- 4 [label="5"];
        3 -- 6 [label="5"];
        }
      ```,
      width: 3cm,
    ),
  )

+ It does not, Kruskal or Prim would give a spanning tree with total weight equal to $14$, while the output of `algo` gives $16$.
  The difference resides in the fact that we grow the spanning tree starting from a fixed root, which might not be the right choice to get a minimum spanning tree.


=

+ First, building a relation is equivalent to building an adjacency matrix of size $n times n$, so choosing for each of the $n^2$ entries if it will be 0 or 1.
  Reflexivity and (anti)symmetry are independent, since they affect the diagonal and the off-diagonal elements, respectively.
  We can thus treat the three properties separately.
  - If a relation is reflexive, we simply have the diagonal elements fixed to 1, so $n$ fewer entries to set.
  - If it is symmetric, we only need to choose the values in the adjacency matrix for the upper triangle part, and then fill the matrix by symmetry. We therefore have $(n (n-1)) / 2$ fewer binary choices to make.
  - If it is antisymmetric, we can also focus on the upper triangle part, but for each entry $(i,j)$, we have three possibilities:
    - have $a_i cancel(rel) a_j$ and $a_j cancel(rel) a_i$
    - have $a_i rel a_j$ and $a_j cancel(rel) a_i$
    - have $a_i cancel(rel) a_j$ and $a_j rel a_i$

  By the product rule, there are thus $2^((n (n-1)) / 2)$ relations which are both reflexive and symmetric, and $3^((n (n-1)) / 2)$ which are both reflexive and antisymmetric.

+ Let $S_R$ and $S_S$ be the sets of reflexive and symmetric relations.
  What we want to compute is
  $ c = abs(overline(S_R) inter overline(S_S)). $
  By De Morgan, this is equal to $c = abs(overline(S_R union S_S))$.

  Since there are $2^(n^2)$ possible relations in total, $c = 2^(n^2) - abs(S_R union S_S)$.

  Then, by the principle of inclusion-exclusion, we get
  $c = 2^(n^2) - abs(S_R) - abs(S_S) + abs(S_R inter S_S)$.

  From the reasoning given in the previous question, we already know all these terms, so finally:
  $
    c = 2^(n^2) - 2^(n^2 - n) - 2^((n^2 + n) / 2) + 2^((n^2 - n) / 2).
  $

=

+ We get
  $
    cases(
      S_1 = (1 + 2 + 3 + 4 + 5 + 6) mod 7 = 21 mod 7 = 0,
      S_2 = (1 + 2 + 4 + 9 + 25 + 36) mod 7 = (1 + 2 + 4 + 2 + 4 + 1) mod 7 = 14 mod 7 = 0,
    )
  $

+ We can rewrite $k$ as $k = 6 q$, with $q in NN$.
  We then get that for all $i in ZZ_6 without {0}, i^k = (i^6)^q$.
  These $i$ are clearly not divisible by $7$, and $7$ is prime so by Fermat's little theorem we know that
  $ i^6 equiv 1 (mod 7) => (i^6)^q equiv 1 (mod 7) => i^k equiv 1 (mod 7). $
  It then follows that
  $
    S_k equiv sum_(i=1)^6 1 (mod 7) equiv 6 (mod 7)
  $

+
  Since $a in ZZ_6 without {0}$, it is relatively prime with $7$, so it has a multiplicative inverse. Thus:
  $
    a i equiv a j (mod 7) <=> i equiv j (mod 7) <=> i = j.
  $
  So whenever we multiply $i in ZZ_6 without {0}$ by $a$, we reach an $m in ZZ_6 without {0}$ which cannot be reached by multiplying another $j in ZZ_6 without {0}$ by $a$.

  // - Base case: since $a in ZZ_6 without {0}$, it is relatively prime with $7$, so it has a multiplicative inverse. So:
  //   $
  //     a i equiv a j (mod 7) <=> i equiv j (mod 7) <=> i = j
  //   $
  // - Inductive step: let's assume the equivalence holds for a given $k in NN^*$.
  //   So given $i,j in ZZ_6 without {0}$, we have
  //   $
  //     a^k i^k equiv a^k j^k (mod 7) <=> i = j
  //   $
  //   Let us now prove the equivalence still holds for $k+1$ by double implication.
  //   Using the fact that $a$, $i$ and $j$ have a multiplicative inverse, we can write
  //   $
  //     a^(k+1) i equiv a^(k+1) j^(k+1) (mod 7) <=> a^k i^k j^(-1) equiv a^k j^k i^(-1) (mod 7)
  //   $
  //   which is equivalent to $i=j$, using the inductive hypothesis.
  //   The equivalence does hold for $k+1$.
  // By induction, it holds for all $k in NN^*$.

  In other words, multiplying by $a$ simply permutes the terms of the sum, so we can write
  $
    a^k S_k equiv (sum_(i=1)^6 (a i)^k) (mod 7) equiv (sum_(j=1)^6 j^k) (mod 7) equiv S_k (mod 7)
  $


+ From above, we have that
  $
    S_k (a^k - 1) equiv 0 (mod 7)
  $
  Now let us take $a$ such that $a^k equiv.not 1 (mod 7) <=> a^k - 1 equiv.not 0 (mod 7)$, which means that $a^k - 1$ admits a multiplicative inverse.
  Multiplying on both sides of the congruence above by this inverse, we get that
  $
    S_k equiv 0 (mod 7).
  $
